services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/poetainos
    depends_on:
      - mariadb
      - php
    networks:
      - network
  php:
    image: php:8.3-fpm
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www/poetainos
    networks:
      - network
  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poetainos
      MYSQL_USER: poetainos
      MYSQL_PASSWORD: poetainos
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network

volumes:
  db-data:

networks:
  network: